aplicacions/urls.py
from django.urls import path, include
from .views import (
    AplicacioLlistatView,
    ModificarGrupsAplicacio,
    AplicacioLlistatGrupsEncarregats,
    ModificarEncarregatsAplicacio 
)
app_name = "aplicacions" 
urlpatterns = [
    path('', AplicacioLlistatView.as_view(), name='llistat-aplicacio'),
    path('gestio_grups_encarregats/llistat_grups_encarregats/<int:pk>/', AplicacioLlistatGrupsEncarregats, name='llistar-grups-encarregats'),
    path('gestio_grups_encarregats/modificar_grups_aplicacio/<int:pk>/',ModificarGrupsAplicacio.as_view() , name='modificar-grups-aplicacio'),
    path('gestio_grups_encarregats/modificar_encarregats_aplicacio/<int:pk>/',ModificarEncarregatsAplicacio.as_view() , name='modificar-encarregats-aplicacio'),
]

portal_aplicacions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacio.urls', namespace="autenticacio")),
    path('aplicacions/', include('aplicacions.urls', namespace="aplicacions")),
    path('aplicacions/projecte_batxillerat/', include('batxillerat_projecte.urls', namespace="batxSeminaris")),
    # Path obligatori allauth
    path('accounts/', include('allauth.urls')),
]

aplicacions/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import Group , User
from .modelManagers import LListaAplicacions


class Aplicacio(models.Model):
    nom = models.CharField(max_length=30)
    descripcio = models.CharField(max_length=200)
    data_limit_inici = models.DateField()
    data_limit_fi = models.DateField()
    url_acces = models.CharField(max_length=60,blank=True)
    url_backend = models.CharField(max_length=60,blank=True)
    llista_grups = models.ManyToManyField(Group,blank=True)
    llista_encarregats = models.ManyToManyField(User,limit_choices_to={"rol__id_rol":1},blank=True) 

    objects = models.Manager()
    llistatAplicacions= LListaAplicacions()

    class Meta:
        verbose_name_plural = 'Aplicacions'

    def __str__(self):
        return self.nom


    def save(self, *args, **kwargs):
        if self.data_limit_inici > self.data_limit_fi:
            raise ValidationError(
                "La Data inici no pot ser mes gran que la fi")
        super(Aplicacio, self).save(*args, **kwargs)

aplicacions/forms.py
from django import forms
from django.contrib.auth.models import Group , User
from .models import Aplicacio
from django.forms import ModelMultipleChoiceField

# Formulari per modificar els grups que tenen accés a una aplicació
class ModificarGrupsAplicacioForm(forms.ModelForm):

    class Meta:
        model = Aplicacio
        fields = ['llista_grups']

    llista_grups = forms.ModelMultipleChoiceField(
        queryset = Group.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

    def __init__(self, *args, **kwargs):
        super(ModificarGrupsAplicacioForm, self).__init__(*args, **kwargs)
        self.fields['llista_grups'].required = False

# Modifica i mostra el nom complert del encarregat en el formulari
class EncarregatsMultipleChoiceField(ModelMultipleChoiceField):
    def label_from_instance(self, obj):
        return obj.get_full_name

# Formulari per modificar els encarregats que tenen accés a una aplicació
class ModificarEncarregatsAplicacioForm(forms.ModelForm):

    class Meta:
        model = Aplicacio
        fields = ['llista_encarregats']

    llista_encarregats = EncarregatsMultipleChoiceField(
        queryset = User.objects.filter(rol__id_rol=1),
        widget=forms.CheckboxSelectMultiple
    )
    def __init__(self, *args, **kwargs):
        super(ModificarEncarregatsAplicacioForm, self).__init__(*args, **kwargs)
        self.fields['llista_encarregats'].required = False

aplicacions/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.urls import reverse_lazy
from .models import Aplicacio
from .forms import ModificarGrupsAplicacioForm,ModificarEncarregatsAplicacioForm
from django.utils.decorators import method_decorator
from .decorators import professor_encarregat

# View que mostra les aplicacions als usuaris
class AplicacioLlistatView(LoginRequiredMixin, generic.ListView):
    template_name = "aplicacions/llistar_aplicacions.html"
    context_object_name = "llista_aplicacions"

    def get_queryset(self):
       aplicacions =  Aplicacio.llistatAplicacions.per_usuari(self.request.user)
       return aplicacions

# View que mostra ens encarregats i els grups d'una aplicació
@login_required
@professor_encarregat
def AplicacioLlistatGrupsEncarregats(request,pk):

    aplicacions =  Aplicacio.llistatAplicacions.per_usuari(request.user)
    aplicacio =  Aplicacio.objects.filter(pk=pk)
    return render(request, 'aplicacions/gestio_grups_encarregats/aplicacio_grups_encarregats.html', {'llista_aplicacions': aplicacions,"aplicacio":aplicacio})


# View per modificar els grups d'una aplicació
class ModificarGrupsAplicacio(LoginRequiredMixin,generic.UpdateView):

    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    template_name = "aplicacions/gestio_grups_encarregats/modificar_grups_aplicacio.html"
    form_class = ModificarGrupsAplicacioForm
    queryset = Aplicacio.objects.all()

    def get_success_url(self):
        return reverse_lazy('aplicacions:llistar-grups-encarregats', kwargs={'pk': self.kwargs['pk']})

# View per modificar els encarregats d'una aplicació
class ModificarEncarregatsAplicacio(LoginRequiredMixin,generic.UpdateView):
    
    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
        
    template_name = "aplicacions/gestio_grups_encarregats/modificar_encarregats_aplicacio.html"
    form_class = ModificarEncarregatsAplicacioForm
    queryset = Aplicacio.objects.all()

    def get_success_url(self):
        return reverse_lazy('aplicacions:llistar-grups-encarregats', kwargs={'pk': self.kwargs['pk']})

aplicacions/templates/aplicacions/gestio_grups_encarregats/aplicacio_grups_encarregats.html
{% extends "aplicacions/llistar_aplicacions.html" %}
{% load static %}
{% block aplicacio %}
<div class="container">
  <div class="row p-1  align-items-center shadow rounded mt-2 pb-4">
    <h4 class="p-3 text-center">Modificar grups i encarregats <br> {{aplicacio.0.nom}} </h4>
    <div class="row">
      <div class="col-xxl-6 col-md-6">
        <div class="card text-center">
          <div class="card-body">
            <h5>Modificar grups
              <button onclick="obrir_modal_modificar_grups_aplicacio('{% url 'aplicacions:modificar-grups-aplicacio' aplicacio.0.id %}')" 
                      class="btn shadow-none p-0 pb-2 pe-2"> 
                      <i  class="bi bi-plus-square align-middle" style="font-size:15px;"></i>
              </button>
            </h5>
            <ol class="list-group list-group-numbered">
              {% for grup in aplicacio.0.llista_grups.all %}
              <li class="list-group-item d-flex justify-content-between align-items-start">
                <div class="ms-2 me-auto">
                  <div class="fw-bold">{{grup}}</div>
                </div>
              </li>
              {% endfor %}
              {% if not aplicacio.0.llista_grups.all %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">No hi han grups assignats </div>
                  </div>
                </li>
              {% endif %}
            </ol>
          </div>
        </div>
      </div>
      <div class="col-xxl-6 col-sm-6">
        <div class="card text-center">
          <div class="card-body">
            <h5>Modificar Encarregats
              <button onclick="obrir_modal_modificar_encarregats_aplicacio('{% url 'aplicacions:modificar-encarregats-aplicacio' aplicacio.0.id %}')" 
                      class="btn shadow-none p-0 pb-2 pe-2"> 
                      <i  class="bi bi-plus-square align-middle" style="font-size:15px;"></i>
              </button>
            </h5>
            <ol class="list-group list-group-numbered">
              {% for encarregat in aplicacio.0.llista_encarregats.all %}
                {% if encarregat %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">{{encarregat.get_full_name}}</div>
                  </div>
                </li>
                {% endif %}
              {% endfor %}
              {% if not aplicacio.0.llista_encarregats.all %}
                <li class="list-group-item d-flex justify-content-between align-items-start">
                  <div class="ms-2 me-auto">
                    <div class="fw-bold">No hi han encarregats </div>
                  </div>
                </li>
              {% endif %}
            </ol>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" tabindex="-1" id="modalModificarGrups" role="dialog"></div>
<div class="modal fade" tabindex="-1" id="modalModificarEncarregats" role="dialog"></div>
{% endblock %}
{% block extrajs %}
  <script type="text/javascript" src="{% static 'js/aplicacions/gestio_encarregat_grups.js' %}"></script>
{% endblock extrajs %}

aplicacions/templates/aplicacions/gestio_grups_encarregats/modificar_encarregats_aplicacio.html
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Modificar Encarregats</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <form action="{% url 'aplicacions:modificar-encarregats-aplicacio' aplicacio.id %}" method="POST">
        {% csrf_token %} 
        <div class="modal-body">
            <div class="row g-3 align-items-center mb-2">
                <div class="col-auto">
                  <label for="encarregat" class="col-form-label">Encarregat:</label>
                </div>
                <div class="col-auto">
                  <input type="text" id="encarregat" class="form-control">
                </div>
            </div>
            <hr>
            {{form}}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>

aplicacions/templates/aplicacions/gestio_grups_encarregats/modificar_grups_aplicacio.html
<div class="modal-dialog">
    <div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title">Modificar grups</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <form action="{% url 'aplicacions:modificar-grups-aplicacio' aplicacio.id %}" method="POST">
        {% csrf_token %} 
        <div class="modal-body">
            {{form}}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-primary">Guardar</button>
        </div>
    </form>
</div>