aplicacions/urls.py
from django.urls import path, include
from .views import (
    AplicacioLlistatView,
    ModificarGrupsAplicacio,
    AplicacioLlistatGrupsEncarregats,
    ModificarEncarregatsAplicacio 
)
app_name = "aplicacions" 
urlpatterns = [
    path('', AplicacioLlistatView.as_view(), name='llistat-aplicacio'),
    path('gestio_grups_encarregats/llistat_grups_encarregats/<int:pk>/', AplicacioLlistatGrupsEncarregats, name='llistar-grups-encarregats'),
    path('gestio_grups_encarregats/modificar_grups_aplicacio/<int:pk>/',ModificarGrupsAplicacio.as_view() , name='modificar-grups-aplicacio'),
    path('gestio_grups_encarregats/modificar_encarregats_aplicacio/<int:pk>/',ModificarEncarregatsAplicacio.as_view() , name='modificar-encarregats-aplicacio'),
]

batxillerat_projecte/urls.py
from django.urls import path, include
app_name = "batxSeminaris"

from .utils import render_pdf_view
from .views import (
    MantenimentFormulari,
    AssignarProjecte,
    CrearDepartament,
    ModificarDepartament,
    EliminarDepartament,
    CrearSeminari,
    ModificarSeminari,  
    EliminarSeminari,
    EnviarSolicitud,
    get_json_seminari_data,
    get_json_departament_data,
    get_json_departament2_data,
)

urlpatterns = [
    path('',EnviarSolicitud, name='enviar-solicitud'),
    path('mantenimentFormulari/', MantenimentFormulari.as_view(), name='manteniment-formulari'),
    path('assignarProjecte/', AssignarProjecte, name='assignar-projecte'),
    path('crear_departament/', CrearDepartament.as_view(), name='crear-departament'),
    path('modificar_departament/<int:pk>/', ModificarDepartament.as_view(), name='modificar-departament'),
    path('eliminar_departament/<int:pk>/', EliminarDepartament.as_view(), name='eliminar-departament'),
    path('crear_seminari/',CrearSeminari.as_view() , name='crear-seminari'),
    path('modificar_seminari/<int:pk>/',ModificarSeminari.as_view() , name='modificar-seminari'),
    path('eliminar_seminari/<int:pk>/',EliminarSeminari.as_view() , name='eliminar-seminari'),
    
    path('seminari-json/<int:departament_id>/', get_json_seminari_data, name='seminari-json'),
    path('departament-json/<int:departament_id>/', get_json_departament_data, name='departament-json'),
    path('departament-json/<int:departament_id>/<int:departament2_id>/', get_json_departament2_data, name='departament-json2'),
    path('assignarProjecte/exportar_pdf/',render_pdf_view,name='exportar-pdf'),
]

portal_aplicacions/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacio.urls', namespace="autenticacio")),
    path('aplicacions/', include('aplicacions.urls', namespace="aplicacions")),
    path('aplicacions/projecte_batxillerat/', include('batxillerat_projecte.urls', namespace="batxSeminaris")),
    # Path obligatori allauth
    path('accounts/', include('allauth.urls')),
]

batxillerat_projecte/models.py
from django.db import models
from django.contrib.auth.models import User

class Departament(models.Model):
    nom = models.CharField(max_length=100)

    def __str__(self):
        return self.nom

class Seminari(models.Model):
    nom = models.CharField(max_length=100)
    departament = models.ForeignKey(Departament, on_delete=models.CASCADE)
    places = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.nom


class Solicitud(models.Model):
    plantajament = models.TextField()
    seminari = models.ForeignKey(Seminari, on_delete=models.CASCADE)
    usuari = models.ForeignKey(User, on_delete=models.CASCADE)
    assignat = models.BooleanField(default=False)

    


   

batxillerat_projecte/forms.py
from django import forms
from .models import Departament, Seminari

# Formulari per  afegir departaments
class DepartamentForm(forms.ModelForm):

    class Meta:
        model = Departament
        fields = ['nom']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs.update({'class': 'form-control'})

# Formulari per  afegir seminaris
class SeminariForm(forms.ModelForm):

    class Meta:
        model = Seminari
        fields = ['nom', 'places','departament']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs.update({'class': 'form-control'})
        self.fields['places'].widget.attrs.update({'class': 'form-control'})
        self.fields['departament'].widget.attrs.update({'id': 'departamentId','class':'d-none'})
        self.fields['departament'].label = False

# Formulari per modificar seminaris
class ModificarSeminariForm(forms.ModelForm):

    class Meta:
        model = Seminari
        fields = ['nom', 'places']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nom'].widget.attrs.update({'class': 'form-control'})
        self.fields['places'].widget.attrs.update({'class': 'form-control'})

batxillerat_projecte/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from django.http import JsonResponse
from django.db.models import Count,Case,When,F
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required,permission_required
from aplicacions.models import Aplicacio
from autenticacio.models import Group
from .models import Departament, Seminari, Solicitud
from .forms import DepartamentForm, SeminariForm,ModificarSeminariForm
from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from .decorators import professor_encarregat,usuari_grup_aplicacio
# Vista d'acces al manteniment del formulari
class MantenimentFormulari(LoginRequiredMixin, generic.ListView):

    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)
    
    template_name = "batx_seminaris/manteniment_formulari.html"
    context_object_name = "llista_manteniment"
    queryset = Departament.objects.all()

# Vista d'acces per assignar projecte als alumnes
@login_required
@professor_encarregat
def AssignarProjecte(request):
    if request.method == 'POST':
        # Al usuari si assigna el seminari i es retorna una llista amb les places recalculades
        solicitudId = request.POST.get('solicitudId')
        usuariId = request.POST.get('usuariId')
        SolicitudsUsuari = Solicitud.objects.filter(usuari_id=usuariId)
        SolicitudsUsuari.filter(assignat=True).update(assignat=False)
        SolicitudsUsuari.filter(id=solicitudId).update(assignat=True)
        placesDisponibles = list(Solicitud.objects.values('seminari').annotate(num_places=F('seminari__places')-Count(Case(When(assignat=True, then=1)))))
        return JsonResponse({'data':placesDisponibles})
    else:
        Solicituds = Solicitud.objects.all()
        grups= Group.objects.filter(curs=3)
        placesDisponibles = Solicitud.objects.values('seminari').annotate(num_places=F('seminari__places')-Count(Case(When(assignat=True, then=1))))
        solicitudsPerId={}
        # Crea objecte amb usuari id de clau i de data les seves solicituds.
        for solicitud in Solicituds:
            solicitudsPerId.setdefault(solicitud.usuari_id, []).append(solicitud)
        llistaSolicitudsId = sorted(solicitudsPerId.items())
        
        return render(request, 'batx_seminaris/assignar_projecte.html', {'llista_solicituds': llistaSolicitudsId,'placesDisponibles':placesDisponibles,"llista_grups":grups})

# Vista modal per crear departament
class CrearDepartament(LoginRequiredMixin, generic.CreateView):

    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    template_name = "batx_seminaris/departament_crud/crear_departament.html"
    form_class = DepartamentForm
    success_url = reverse_lazy("batxSeminaris:manteniment-formulari")

# Vista modal per modificar departament
class ModificarDepartament(LoginRequiredMixin, generic.UpdateView):
    
    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    template_name = "batx_seminaris/departament_crud/modificar_departament.html"
    form_class = DepartamentForm
    success_url = reverse_lazy("batxSeminaris:manteniment-formulari")
    queryset = Departament.objects.all()

# Vista modal per eliminar departament
class EliminarDepartament(LoginRequiredMixin, generic.DeleteView):
    
    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    template_name = "batx_seminaris/departament_crud/eliminar_departament.html"
    success_url = reverse_lazy("batxSeminaris:manteniment-formulari")
    queryset = Departament.objects.all()

# Vista modal per crear seminari
class CrearSeminari(LoginRequiredMixin, generic.CreateView):
    
    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    template_name = "batx_seminaris/seminari_crud/crear_seminari.html"
    form_class = SeminariForm
    success_url = reverse_lazy("batxSeminaris:manteniment-formulari")

# Vista modal per modificar seminari
class ModificarSeminari(LoginRequiredMixin, generic.UpdateView):
    
    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    template_name = "batx_seminaris/seminari_crud/modificar_seminari.html"
    form_class = ModificarSeminariForm
    success_url = reverse_lazy("batxSeminaris:manteniment-formulari")
    queryset = Seminari.objects.all()

# Vista modal per eliminar seminari
class EliminarSeminari(LoginRequiredMixin, generic.DeleteView):

    @method_decorator(professor_encarregat)
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)

    template_name = "batx_seminaris/seminari_crud/eliminar_seminari.html"
    success_url = reverse_lazy("batxSeminaris:manteniment-formulari")
    queryset = Seminari.objects.all()


# View pagina principal solicitud
@login_required
@usuari_grup_aplicacio
def EnviarSolicitud(request):
    if request.method == 'POST':
        user = request.user
        seminariPrimeraOpcio = request.POST.get('seminariPrimeraOpcio')
        seminariSegonaOpcio = request.POST.get('seminariSegonaOpcio')
        seminariTerceraOpcio = request.POST.get('seminariTerceraOpcio')

        seminariOpcio1 = get_object_or_404(Seminari, pk=seminariPrimeraOpcio)
        seminariOpcio2 = get_object_or_404(Seminari, pk=seminariSegonaOpcio)
        seminariOpcio3 = get_object_or_404(Seminari, pk=seminariTerceraOpcio)

        solicitud = Solicitud(seminari=seminariOpcio1,usuari=user,plantajament=request.POST.get('plantajamentPrimeraOpcio'))
        solicitud.save()

        solicitud2 = Solicitud(seminari=seminariOpcio2,usuari=user,plantajament=request.POST.get('plantajamentSegonaOpcio'))
        solicitud2.save()


        solicitud3 = Solicitud(seminari=seminariOpcio3,usuari=user,plantajament=request.POST.get('plantajamentSegonaOpcio'))
        solicitud3.save()

        return JsonResponse({'success': True}, status=201)
    else:
        aplicacions = Aplicacio.llistatAplicacions.per_usuari(request.user)
        solicituds =  Solicitud.objects.filter(usuari=request.user)
        if(solicituds.count() >=3):
            return render(request, 'batx_seminaris/solicitud_enviada.html',{'llista_aplicacions':aplicacions,"llista_solicituds":solicituds})
        else:    
            departaments = Departament.objects.values()
            return render(request, 'batx_seminaris/enviar_solicitud.html', {'llista_aplicacions':aplicacions,'llista_departaments':departaments})

# vista que retorna un dicionari de seminaris a partir d'un departament
@login_required
def get_json_seminari_data(request, *args, **kwargs):
    selected_departament = kwargs.get('departament_id')
    obj_seminaris = list(Seminari.objects.filter(departament__id=selected_departament).values())
    return JsonResponse({'data':obj_seminaris})
@login_required
# vista que retorna un dicionari de departaments  diferent al departament selecionat anteriorment
def get_json_departament_data(request, *args, **kwargs):
    selected_departament = kwargs.get('departament_id')
    obj_departaments = list(Departament.objects.exclude(id=selected_departament).values())
    return JsonResponse({'data':obj_departaments})
@login_required
# vista que retorna un dicionari de departaments  diferent als dos departament selecionats anteriorment
def get_json_departament2_data(request, *args, **kwargs):
    selected_departament = kwargs.get('departament_id')
    selected_departament2 = kwargs.get('departament2_id')
    ex=[selected_departament,selected_departament2]
    obj_departaments = list(Departament.objects.exclude(id__in=ex).values())
    return JsonResponse({'data':obj_departaments})

batxillerat_projecte/templates/batx_seminaris/assignar_projecte.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div id="wrapper">
  <div class="container-fluid">
      <!-- Sidebar -->
      <div id="sidebar-wrapper">
          <ul class="sidebar-nav">
              <div class="row d-flex justify-content-center">
                  <div class="col-11">
                      <div class="row">
                          <div class="col-11 text-white">
                              <ul>
                                  <li class="colorNavLink fs-5 nav-link pt-4 ps-1 text-center colorNavModificat">Administració </br>Temes Projecte</li>
                                  <div style="background-color:#EAEFF5;height:1px;"></div>
                                  <li class="colorNavLink rounded nav-link mt-4 bg-secondary" role="button">
                                    <div class="row">
                                      <div class="col-sm-2  pt-1">
                                        <i class="bi bi-clipboard-data me-3" style="font-size:20px;"></i>
                                      </div>
                                      <div class="col-sm-8 pe-2  me-4">
                                          Assignar<br>Projecte
                                      </div>
                                    </div>
                                  </li>
                                  <li onclick = "location.href= '{% url 'batxSeminaris:manteniment-formulari' %}'" class=" colorNavLink nav-link color-boto rounded mt-1" role="button">
                                      <div class="row">
                                        <div class="col-sm-2 pt-1">
                                            <i class="bi bi-gear-wide" style="font-size:20px;" ></i>
                                        </div>
                                        <div class="col-sm-8">
                                            Manteniment <br> Formulari
                                        </div>
                                      </div>
                                    </li>
                              </ul>
                          </div>
                      </div>
                  </div>
              </div>
          </ul>
      </div>
      <!-- Page Content -->
      <div id="page-content-wrapper" class="overflow-auto" style="height:85vh">
          <div class="container-fluid">
            <div class="col p-1 ps-5">
              <div class="container p-2">
                <div class="row py-4">
                    <div class="col-sm-4">
                      <h5>Llistat Sol·licituds</h5>
                    </div>
                    <div class="col-sm-5"></div>
                    <div class="col-sm-2 ms-3">
                        <button onclick = "location.href= '{% url 'batxSeminaris:exportar-pdf' %}'" type="button" class="btn btn-outline-secondary btn-sm">Exportar LListat</button>
                    </div>
                </div>
                <div class="row d-flex justify-content-between">
                  <div class="col-auto">
                    <label for="grup" class="col-form-label">Grup:</label>
                    <div>
                      <select class="form-select" id="filter">
                        <option selected value="Tots">---</option>
                        {% for grup in llista_grups %}
                          <option value="{{grup}}">{{grup}}</option>
                        {% endfor %}
                      </select>
                    </div>
                  </div>
                  <div class="col-sm-4">
                    <label for="alumne" class="col-form-label">Alumne:</label>
                    <div class="col-md-9">
                      <input type="input" id="alumne" class="form-control">
                    </div>
                  </div>
                </div>
                <div class="row py-2">
                  <form id="defaults" >
                      <input name="csrfmiddlewaretoken" type="hidden" value="{{ csrf_token }}">
                  </form>
                  <div class="col-md-11 py-5">
                    <table class=" table-responsive table table-sm table-hover">
                      <thead>            
                        <tr>
                            <th>Alumne</th>
                            <th class="text-center">Primera Opció</th>
                            <th class="text-center">Segona Opció</th>
                            <th class="text-center">Tercera Opció</th>
                            <th class="text-center">Plantajament</th>
                        </tr>
                      </thead>
                      <tbody id="taulaSolicituds">
                        {% for key, value in llista_solicituds %}
                          <tr grup="{{value.0.usuari.groups.all.0}}">
                            <td>{{value.0.usuari.get_full_name}}</td>
                              {% for solicitud in value %}
                                <td>
                                  <span data-bs-toggle="popover"  
                                        data-bs-trigger="hover" 
                                        data-bs-placement="top"
                                        data-bs-content="Places Disponibles: {% for places in placesDisponibles %}{% if solicitud.seminari_id == places.seminari %}{{places.num_places}}{% endif %} {% endfor %} " >
                                    <button 
                                      type="button" 
                                      class="btn btn-outline-dark w-100 {% if solicitud.assignat == True %}active{% endif %}"
                                      {% for places in placesDisponibles %}{% if solicitud.seminari_id == places.seminari %}{% if places.num_places == 0 %}disabled='disabled'{% endif %}{% endif %} {% endfor %}
                                      usuari-id="{{solicitud.usuari_id}}" 
                                      solicitud-id="{{solicitud.id}}"
                                      seminari-id="{{solicitud.seminari_id}}" >{{solicitud.seminari}}</button>
                                  </span>
                                </td>
                              {% endfor %}
                              <td>
                                <button type="button" 
                                        class="btn btn-outline-dark w-100" 
                                        data-bs-toggle="collapse" 
                                        data-bs-target="#mostrar{{key}}" 
                                        aria-controls="mostrar{{key}}">Mostrar</button>
                              </td>
                          </tr>
                          <tr class="noBorder">
                            <td colspan="5" class=" p-0">
                              <div class="collapse" id="mostrar{{key}}">
                                <div class="accordion" id="accordionExample">
                                  {% for solicitud in value %}
                                  <div class="accordion-item">
                                    <h2 class="accordion-header" id="headingTwo">
                                      <button class="accordion-button collapsed" 
                                              type="button" 
                                              data-bs-toggle="collapse" 
                                              data-bs-target="#accordion{{key}}{{solicitud.seminari|cut:' '}}" 
                                              aria-expanded="false" 
                                              aria-controls="accordion{{key}}{{solicitud.seminari|cut:' '}}">
                                        <h6>{{solicitud.seminari}}</h6>
                                      </button>
                                    </h2>
                                    <div id="accordion{{key}}{{solicitud.seminari|cut:' '}}" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                                      <div class="accordion-body">
                                        {{solicitud.plantajament}}
                                      </div>
                                    </div>
                                  </div>
                                  {% endfor %}
                                </div>
                              </div>
                            </td>
                          </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>   
            </div>
          </div>
      </div>
  </div>
</div>
{% endblock %}
{% block extrajs %}
  <script type="text/javascript" src="{% static 'js/batxilleratProjecte/assignarProjecte.js' %}"></script>
{% endblock extrajs %}

batxillerat_projecte/templates/batx_seminaris/exportar_pdf.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LLista alumnes i seminaris</title>
  </head>
  <style>
    @page {
        size: "A4";
        margin: 2.0cm 3cm 3.5cm 3cm;
    }
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 3px;
      text-align: left;
    }
    #page{
      width: 1000px;
    }
    </style>
  <body>
    <div id="page">
      <h1>LListat Alumnat i Seminaris</h1>
      <table id="tables">
          <tr>
              <th colspan="1">Nom Alunme</th>
              <th colspan="1">Tema Assignat</th>
              <th colspan="1">Grup</th>
          </tr>
          {% for solicitud  in llistaSolicituds  %}
          <tr>
              <td colspan="1">{{solicitud.usuari.get_full_name}}</td>
              <td colspan="1">{{solicitud.seminari}}</td>
              <td colspan="1">{{solicitud.usuari.groups.all.0}}</td>
          </tr>
          {% endfor %}
      </table>
    </div>
  </body>
</html>

batxillerat_projecte/templates/batx_seminaris/manteniment_formulari.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div id="wrapper">
    <div class="container-fluid">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <div class="row d-flex justify-content-center">
                    <div class="col-11">
                        <div class="row">
                            <div class="col-11 text-white">
                                <ul>
                                    <li  class="colorNavLink fs-5 nav-link pt-4 ps-1 text-center">Administració </br>Temes Projecte</li>
                                    <div style="background-color:#EAEFF5;height:1px;"></div>
                                    <li onclick = "location.href= '{% url 'batxSeminaris:assignar-projecte' %}'" class="colorNavLink rounded nav-link color-boto mt-4" role="button">
                                      <div class="row">
                                        <div class="col-sm-2  pt-1">
                                          <i class="bi bi-clipboard-data me-3" style="font-size:20px;"></i>
                                        </div>
                                        <div class="col-sm-8 pe-2  me-4">
                                            Assignar<br>Projecte
                                        </div>
                                      </div>
                                    </li>
                                    <li class="colorNavLink nav-link bg-secondary rounded mt-1" role="button">
                                        <div class="row">
                                          <div class="col-sm-2 pt-1">
                                              <i class="bi bi-gear-wide" style="font-size:20px;" ></i>
                                          </div>
                                          <div class="col-sm-8">
                                              Manteniment <br> Formulari
                                          </div>
                                        </div>
                                      </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </ul>
        </div>
        <!-- Page Content -->
        <div id="page-content-wrapper" class="overflow-auto" style="height:88vh">
            <div class="container-fluid">
                <div class="col pt-2" style="margin-left: 100px; margin-bottom: 100px;" >
                    <div class="container">
                        <h2 class="pt-3 pb-4">Departaments i seminaris</h2>
                        <div class="row">
                            <div class="col-md-10">
                                <table class="table-responsive  table table-sm table-hover">
                                    <thead class="align-middle">            
                                        <tr>
                                            <th colspan="4">
                                                <button onclick="obrir_modal_crear_departament('{% url 'batxSeminaris:crear-departament' %}')" class="btn shadow-none p-0 pb-2 pe-2"> <i  class="bi bi-plus-square align-middle" style="font-size:15px;"></i></button>
                                                Nou Departament
                                            </th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for departament in llista_manteniment %}
                                            <!-- departaments -->
                                            <tr class="align-middle">
                                                <td class="text-nowrap" style="width: 5%;">
                                                    <button onclick="obrir_modal_crear_seminari('{% url 'batxSeminaris:crear-seminari' %}');reply_click(this.value);" value="{{ departament.id}}" id="botoCrearSeminari" class="btn shadow-none px-0"> <i class="bi bi-plus-square"></i></button>
                                                    <button onclick="obrir_modal_modificar_departament('{% url 'batxSeminaris:modificar-departament' departament.id %}')" class="btn shadow-none px-2"> <i class="bi bi-pencil-square"></i></button> 
                                                </td>                     
                                                <td colspan="2" class="pt-2 px-2" style="text-align:left;"><h5>{{departament.nom}}</h5></td>                 
                                                <td style="text-align:right" >
                                                    <button onclick="obrir_modal_eliminar_departament('{% url 'batxSeminaris:eliminar-departament' departament.id %}')" class="btn shadow-none"> <i class="bi bi-x-square"></i></button>
                                                </td>
                                            </tr>
                                            {% for seminari in departament.seminari_set.all %}
                                                <!-- Seminaris -->
                                                <tr class="align-middle borderless">
                                                    <td></td>
                                                    <td colspan="2">
                                                        <i class="bi bi-circle-fill px-4" style="font-size:12px;"></i>
                                                        <button onclick="obrir_modal_modificar_seminari('{% url 'batxSeminaris:modificar-seminari' seminari.id %}')" class="btn shadow-none px-0"> <i class="bi bi-pencil-square"></i></button>
                                                        <button onclick="obrir_modal_eliminar_seminari('{% url 'batxSeminaris:eliminar-seminari' seminari.id %}')" class="btn shadow-none px-0 ps-1"> <i class="bi bi-x-square"></i></button>
                                                        <span class="ps-3 pt-3">{{seminari.nom}}</span>
                                                    </td>
                                                    <td class="text-nowrap" style="text-align:right">
                                                        Places Disponibles: {{seminari.places}}  
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>      
                        </div>        
                    </div>
                    <div class="modal fade" tabindex="-1" id="modalAfegirDepartament" role="dialog"></div>
                    <div class="modal fade" tabindex="-1" id="modalModificarDepartament" role="dialog"></div>
                    <div class="modal fade" tabindex="-1" id="modalEliminarDepartament" role="dialog"></div>
                    <div class="modal fade" tabindex="-1" id="modalAfegirSeminari" role="dialog"></div>
                    <div class="modal fade" tabindex="-1" id="modalModificarSeminari" role="dialog"></div>
                    <div class="modal fade" tabindex="-1" id="modalEliminarSeminari" role="dialog"></div>
                </div>
            </div>
        </div>
    </div>
</div>
{% block extrajs %}
  <script type="text/javascript" src="{% static 'js/batxilleratProjecte/mantenimentFormulari.js' %}"></script>
{% endblock extrajs %}
{% endblock %}